### ISSUE TITLE
Error when installing Carto skeleton app

### ISSUE THREAD

**Issue by jaballogian** [CartoDB/carto-react-template#227]
Hello,

I tried to create a react app using Carto templates from these documentations:
1. https://docs.carto.com/react/overview/
2. https://docs.carto.com/react/guides/getting-started/

When I tried to create a react app with the skeleton template using:
```bash
npx create-react-app carto-skeleton-app --template @carto
```

there was an error:
```bash
E:\<username>\Exercises\React-Js> npx create-react-app carto-skeleton-app --template @carto
error: option '--template <path-to-template>' argument missing
E:\<username>\Exercises\React-Js>
```

But when I tried to create a react app with the sample app template using:
```bash
npx create-react-app carto-skeleton-app --template @carto/sample-app
```

the app was successfully created.

This is not a big deal for me because I can use the sampe app.
I just want to inform you about this.

Here are my environments:
1. NPM version: 6.14.8
2. Node version: 12.19.0
3. OS: Windows 10 Home 64-bit built 19042

**Comment by borja-munoz** [comment]
Hi,

Thanks for the information.

This might be caused by an outdated create-react-app version. Could you please try uninstalling any create-react-app version that you might have and then executing the instruction again?

**Comment by borja-munoz** [comment]
Hi again,

This could also be caused if you are using PowerShell for executing the `npx create-react-app` instruction because it does not interpret correctly the `@carto` parameter due to the use of `@` symbol as an operator in PowerShell. 

Please note that PowerShell is the default shell if using the integrated terminal in Visual Studio Code ([reference](https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles)).

If using PowerShell, you need to wrap the template name in single quotes:

`npx create-react-app carto-skeleton-app --template '@carto'`
