### ISSUE TITLE
Carto for React + deck.gl/react (react-map-gl) component, are they compatible?

### ISSUE THREAD

**Issue by plgagnon2** [CartoDB/carto-react-template#272]
(I dont know where I can ask for help with this. If you know about a forum or whatever where I could ask for help, please comment)

I am using Carto for React for the first time, I built my app using this (https://docs.carto.com/react/guides/getting-started/)
i.e. `npx create-react-app my-app --template @carto`

I am trying to incorporate `react-map-gl` component into it. I tried adding it into `Main.js` like this:

```
...
import {FullscreenControl} from 'react-map-gl';
...
<Grid item className={`${classes.mapWrapper} ${isGmaps ? classes.gmaps : ''}`}>
        <Map layers={getLayers()} />

        <FullscreenControl style={{
          right: 10,
          top: 10
        }} />
...
```

...fullscreen button appears but I keep getting this error when I click on it
![image](https://user-images.githubusercontent.com/80784116/132110981-22740126-3ee0-42a0-88ee-c78ae45bbd8d.png)

Tried a bunch of components here (https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control) and I mostly get errors too. Are those 2 libs compatible or am I trying to do something pointless?

p.s. sorry english not my first language :P

**Comment by borja-munoz** [comment]
Hi @plgagnon2, you can ask here but you can also use the CARTO Users Slack workspace that you can join here:
https://join.slack.com/t/cartousercommunity/shared_invite/zt-t7t7k5s4-3c4pZJLrLlkVow3AEDt~ZQ

CARTO for React uses deck.gl for visualization. The template includes a `Map` component that takes advantage of the <DeckGL> [React component](https://deck.gl/docs/get-started/using-with-react#the-deckgl-react-component). This component already works with the react-map-gl component, so you don't need to add it.

**Comment by plgagnon2** [comment]
So how would I add lets say a `FullscreenControl`?

**Comment by borja-munoz** [comment]
We are using `StaticMap` from react-map-gl and I'm not sure is compatible with `FullScreenControl`. We use `StaticMap` instead of `InteractiveMap` because it is the deck.gl recommendation.

We don't provide a full screen control in the CARTO for React templates but it shouldn't be too difficult to implement one. You can get inspiration by looking at the `ZoomControl` in the `src/components/common` folder for the UI. You could the use the [FullScreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) or any other library that provides full screen functionality.

**Comment by plgagnon2** [comment]
not compatible but easy to do from ZoomControl
